### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by cronlabspl** [labspl/colors.js#20]
- [x] Review and improve all project files,
- [ ] Create as many drafts as needed,
- [ ] Create tags ( optional, except for release tag; TBD ),
- [x] Create new branch only for releases ( [Stable](https://github.com/labspl/colors.js/tree/stable) ),
- [x] #19,
- [x] Create milestone
- [x] Fix according to hints from Codacy ( >> #33 #22 #32 #31 )
